pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import qs.Commons
import qs.Services.UI

// Niri session init: composes ~/.config/niri/atmosphera-session.kdl
// (user's base config + atmosphera layers) and switches the running niri
// to it via niriqml's LoadConfigFile action. The user's own config.kdl
// is never modified by this path.
//
// Base config detection: the /proc cmdline/environ of the niri process
// hosting this session (frozen at exec time, so immune to self-inclusion
// after a previous switch). PID resolution prefers niriqml's
// NiriConnection.peerInfo.pid (SO_PEERCRED) and falls back to scanning
// /proc/*/fd for the process holding $NIRI_SOCKET open.
Singleton {
  id: root

  readonly property string xdgConfigHome: {
    var x = Quickshell.env("XDG_CONFIG_HOME");
    return (x && x.length > 0) ? x : Quickshell.env("HOME") + "/.config";
  }
  readonly property string niriDir: xdgConfigHome + "/niri"
  readonly property string sessionConfig: niriDir + "/atmosphera-session.kdl"
  readonly property string baselineSource: Quickshell.shellDir + "/Configs/niri/atmosphera.kdl"

  function init() {
    if (!Quickshell.env("NIRI_SOCKET")) {
      Logger.d("NiriSessionInit", "NIRI_SOCKET unset — not hosted by niri, skipping");
      return;
    }
    Logger.i("NiriSessionInit", "Composing niri session config");
    ipcLoader.active = true;
    _generate();
  }

  function _generate() {
    var peerPid = "";
    if (ipcLoader.item && ipcLoader.item.peerPid > 0)
      peerPid = String(ipcLoader.item.peerPid);

    var env = "none";
    try {
      env = Settings.data.bindings.environment || "none";
    } catch (e) {}

    // NOTE: no ${} expansions inside — this script is embedded in a JS
    // template literal below, where ${ would be interpolated by JS.
    var script = `set -e
DIR="$1"; BASELINE_SRC="$2"; PEER_PID="$3"; ENVV="$4"; SESSION_FILE="$5"
mkdir -p "$DIR"
[ -f "$DIR/atmosphera.kdl" ] || cp "$BASELINE_SRC" "$DIR/atmosphera.kdl"

PID="$PEER_PID"
if [ -z "$PID" ]; then
  INODE=$(stat -Lc %i "$NIRI_SOCKET" 2>/dev/null || true)
  if [ -n "$INODE" ]; then
    for fd_dir in /proc/[0-9]*/fd; do
      if ls -l "$fd_dir" 2>/dev/null | grep -q "socket:\\\\[$INODE\\\\]"; then
        PID=$(echo "$fd_dir" | cut -d/ -f3)
        break
      fi
    done
  fi
fi

BASE=""
if [ -n "$PID" ]; then
  BASE=$(tr '\\0' '\\n' < "/proc/$PID/cmdline" 2>/dev/null | awk '/^(-c|--config)$/{getline; print; exit} /^--config=/{sub(/^--config=/,""); print; exit}' || true)
  if [ -z "$BASE" ]; then
    BASE=$(tr '\\0' '\\n' < "/proc/$PID/environ" 2>/dev/null | sed -n 's/^NIRI_CONFIG=//p' | head -1 || true)
  fi
fi
[ -n "$BASE" ] || BASE="$DIR/config.kdl"

{
  echo "// Generated by Atmosphera. Do not edit — regenerated on shell start."
  echo "// Base config detected at niri boot: $BASE"
  if [ -f "$BASE" ]; then
    if [ "$(dirname "$BASE")" = "$DIR" ]; then
      echo "include \\"$(basename "$BASE")\\""
    else
      echo "include \\"$BASE\\""
    fi
  fi
  echo 'include "atmosphera.kdl"'
  if [ "$ENVV" = "macos" ] && [ -f "$DIR/atmosphera-shortcuts-macos.kdl" ]; then
    echo 'include "atmosphera-shortcuts-macos.kdl"'
  fi
} > "$SESSION_FILE"
`;

    var proc = Qt.createQmlObject(`
      import QtQuick
      import Quickshell.Io
      Process {
        command: ["sh", "-c", ${JSON.stringify(script)}, "sh",
                  "${root.niriDir}", "${root.baselineSource}", "${peerPid}", "${env}", "${root.sessionConfig}"]
        stderr: StdioCollector {}
      }
    `, root, "NiriSessionGenerate");

    proc.exited.connect(function (exitCode) {
      if (exitCode === 0) {
        Logger.i("NiriSessionInit", "Session config written:", root.sessionConfig);
        root._activate();
      } else {
        Logger.e("NiriSessionInit", "Session config generation failed:", String(proc.stderr.text || ""));
      }
      proc.destroy();
    });
    proc.running = true;
  }

  function _activate() {
    if (ipcLoader.item) {
      ipcLoader.item.activate(sessionConfig);
    }
    // No niriqml → no IPC path, and deliberately no CLI fallback: the shell
    // relies on the QML library by design. The config file is still composed
    // and will activate on a later start once qt6-niriqml is installed; the
    // user was already notified from the Loader error path.
  }

  // Regenerate + reload when the bindings environment changes
  Connections {
    target: Settings.data.bindings
    function onEnvironmentChanged() {
      if (Quickshell.env("NIRI_SOCKET")) {
        Logger.i("NiriSessionInit", "Bindings environment changed — regenerating session config");
        root._generate();
      }
    }
  }

  property bool _toastShown: false

  // niriqml-backed IPC (optional dep); loaded only when present
  Loader {
    id: ipcLoader
    active: false
    source: "NiriSessionIpc.qml"
    onStatusChanged: {
      if (status === Loader.Error) {
        Logger.w("NiriSessionInit", "niriqml unavailable — niri session config will not activate");
        if (!root._toastShown) {
          root._toastShown = true;
          ToastService.showWarning(I18n.tr("toast.niriqml-missing") || "Degraded niri experience", I18n.tr("toast.niriqml-missing-desc") || "Install qt6-niriqml to enable niri integration (workspaces, windows, keybinds, session config).", 8000);
        }
      }
    }
  }
}
