name: Mirror to Codeberg

on:
  push:
    branches:
      - '**'
  delete:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone bare repository
        run: git clone --bare https://github.com/noctalia-dev/noctalia-shell.git repo

      - name: Push mirror to Codeberg
        run: |
          cd repo
          git push --mirror https://${{ secrets.CODEBERG_TOKEN }}@codeberg.org/noctalia-dev/noctalia-shell.git